"""
NFN v4.0 — Hyper-Network for Instant In-Context Adaptation

A standard model's weights are fixed at inference time.
A hyper-network generates weight *deltas* (LoRA-style) from the
current context, enabling the model to adapt its behaviour to the
task at hand without any gradient update.

Theory (Ha et al. 2016 "HyperNetworks"; Hu et al. 2021 "LoRA"):
  For each linear layer W ∈ R^{d_out × d_in}, the effective weight is:
      W_eff = W + ΔW,   ΔW = A · B   (rank-r decomposition)

  where A ∈ R^{d_out × r}, B ∈ R^{r × d_in} are generated by the
  hyper-network from the current task embedding z:
      A = H_A(z),  B = H_B(z)

  This is LoRA, but generated from context rather than trained.

NFN twist — phase-conditioned adaptation:
  The task embedding z is derived from the goal phase θ* (if set) or
  from the condensate projection of the context.  This means:
    • When a goal is set: the model literally changes its weights to
      pursue that goal (not just the Kuramoto forcing — actual weights)
    • At inference: zero extra parameters (ΔW is computed on the fly)
    • Gradient flows through z → A, B → ΔW → output

Architecture:
  HyperAdapter      : generates (A, B) from task embedding z
  HyperLinear       : drop-in replacement for nn.Linear with ΔW
  ContextHyperNet   : full hyper-network, generates adapters for all
                      key linear layers in a block from one context vector

This is qualitatively different from LoRA fine-tuning:
  LoRA: A, B are trained parameters (fixed at inference)
  HyperNet: A, B are computed from context (change every forward pass)

Result: zero-shot task adaptation without any gradient update.
"""

import math
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


# ─────────────────────────────────────────────────────────────────────────────
# Hyper-Adapter
# ─────────────────────────────────────────────────────────────────────────────

class HyperAdapter(nn.Module):
    """
    Generates a rank-r LoRA delta (A, B) from a context vector z.

    A: [d_out, r]  generated by H_A: z → d_out × r
    B: [r, d_in]   generated by H_B: z → r × d_in

    ΔW = A · B ∈ R^{d_out × d_in}

    Initialised so that ΔW ≈ 0 at the start (B init to zero).
    """

    def __init__(
        self,
        z_dim:   int,   # context embedding dimension
        d_out:   int,   # target layer output dimension
        d_in:    int,   # target layer input dimension
        rank:    int = 4,
        scale:   float = 0.01,   # ΔW scale (keep small for stability)
    ):
        super().__init__()
        self.d_out  = d_out
        self.d_in   = d_in
        self.rank   = rank
        self.scale  = scale

        # A generator: z → d_out × rank
        self.gen_A = nn.Linear(z_dim, d_out * rank)
        nn.init.normal_(self.gen_A.weight, std=0.01)
        nn.init.zeros_(self.gen_A.bias)

        # B generator: z → rank × d_in  (init to zero → ΔW ≈ 0 at start)
        self.gen_B = nn.Linear(z_dim, rank * d_in)
        nn.init.zeros_(self.gen_B.weight)
        nn.init.zeros_(self.gen_B.bias)

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        """
        z: [B, z_dim]
        Returns ΔW: [B, d_out, d_in]
        """
        B = z.shape[0]
        A = self.gen_A(z).view(B, self.d_out, self.rank)     # [B, d_out, r]
        B_ = self.gen_B(z).view(B, self.rank, self.d_in)     # [B, r, d_in]
        dW = torch.bmm(A, B_) * self.scale                   # [B, d_out, d_in]
        return dW


# ─────────────────────────────────────────────────────────────────────────────
# Hyper-Linear
# ─────────────────────────────────────────────────────────────────────────────

class HyperLinear(nn.Module):
    """
    Drop-in replacement for nn.Linear that accepts an optional context
    vector z and applies a hyper-generated ΔW.

    x @ (W + ΔW(z))ᵀ + b

    When z=None, behaves exactly like a standard nn.Linear.
    """

    def __init__(
        self,
        in_features:  int,
        out_features: int,
        z_dim:        int,
        rank:         int   = 4,
        bias:         bool  = True,
        scale:        float = 0.01,
    ):
        super().__init__()
        self.linear  = nn.Linear(in_features, out_features, bias=bias)
        self.adapter = HyperAdapter(z_dim, out_features, in_features, rank, scale)
        self._z: Optional[torch.Tensor] = None   # cached context

    def set_context(self, z: torch.Tensor):
        """z: [B, z_dim] — set context for subsequent forward calls."""
        self._z = z

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """x: [B, L, in_features] → [B, L, out_features]"""
        out = self.linear(x)
        if self._z is not None:
            B = x.shape[0]
            dW = self.adapter(self._z)   # [B, out, in]
            # Apply per-sample weight delta: einsum boi, bli -> blo
            delta = torch.einsum("boi,bli->blo", dW, x)
            out = out + delta
        return out


# ─────────────────────────────────────────────────────────────────────────────
# Context Hyper-Network
# ─────────────────────────────────────────────────────────────────────────────

class ContextHyperNet(nn.Module):
    """
    Full hyper-network for one AGIBlock.

    Generates context-conditioned ΔW for the key linear layers:
      - Q, K, V projections in attention (3 adapters)
      - FFN up/down projections (2 adapters)

    Context z is derived from:
      1. Goal phase θ* (if set)        — shape [B, n_phases]
      2. Input summary h.mean(1)       — shape [B, d_model]
      Combined via a small encoder.

    Usage:
      hyper = ContextHyperNet(d_model, n_phases, rank=4)
      z     = hyper.encode_context(h, goal_phase)
      hyper.apply_to_block(block, z)   # injects context into HyperLinears
    """

    def __init__(
        self,
        d_model:  int,
        n_phases: int,
        rank:     int   = 4,
        z_dim:    int   = 64,
        scale:    float = 0.02,
    ):
        super().__init__()
        self.z_dim    = z_dim
        self.n_phases = n_phases

        # Context encoder: (h_summary + goal_phase) → z
        in_dim = d_model + n_phases
        self.encoder = nn.Sequential(
            nn.Linear(in_dim, z_dim * 2),
            nn.SiLU(),
            nn.Linear(z_dim * 2, z_dim),
            nn.LayerNorm(z_dim),
        )
        nn.init.zeros_(self.encoder[-2].weight)
        nn.init.zeros_(self.encoder[-2].bias)

        # One adapter per target layer (Q, K, V, FFN_up, FFN_down)
        self.adapters = nn.ModuleDict({
            "q":       HyperAdapter(z_dim, d_model, d_model, rank, scale),
            "k":       HyperAdapter(z_dim, d_model, d_model, rank, scale),
            "v":       HyperAdapter(z_dim, d_model, d_model, rank, scale),
            "ffn_up":  HyperAdapter(z_dim, d_model * 4, d_model, rank, scale),
            "ffn_down":HyperAdapter(z_dim, d_model, d_model * 4, rank, scale),
        })

    def encode_context(
        self,
        h:          torch.Tensor,            # [B, L, d]
        goal_phase: Optional[torch.Tensor],  # [B, n_phases] or None
    ) -> torch.Tensor:
        """Returns context embedding z [B, z_dim]."""
        h_summary = h.mean(1)                # [B, d]
        if goal_phase is None:
            goal_phase = torch.zeros(
                h.shape[0], self.n_phases, device=h.device
            )
        inp = torch.cat([h_summary, goal_phase], dim=-1)   # [B, d+n_phases]
        return self.encoder(inp)                             # [B, z_dim]

    def get_deltas(self, z: torch.Tensor) -> Dict[str, torch.Tensor]:
        """Returns ΔW dict for each adapter key. z: [B, z_dim]."""
        return {name: adapter(z) for name, adapter in self.adapters.items()}

    def forward(
        self,
        h:          torch.Tensor,
        goal_phase: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Dict[str, torch.Tensor]]:
        """
        h: [B, L, d]
        Returns (z [B, z_dim], deltas dict).
        """
        z      = self.encode_context(h, goal_phase)
        deltas = self.get_deltas(z)
        return z, deltas


# ─────────────────────────────────────────────────────────────────────────────
# Hyper-Residual  (lightweight version — no weight generation)
# ─────────────────────────────────────────────────────────────────────────────

class HyperResidual(nn.Module):
    """
    Simpler alternative: instead of generating weight matrices,
    generate a residual activation to add to the hidden state.

    h_adapted = h + scale · MLP(z) · h   (element-wise modulation)

    This is FiLM (Feature-wise Linear Modulation) conditioned on context.
    Cheaper than full ΔW generation but still enables task adaptation.
    """

    def __init__(self, d_model: int, z_dim: int):
        super().__init__()
        self.gate = nn.Sequential(
            nn.Linear(z_dim, d_model),
            nn.Sigmoid(),
        )
        self.shift = nn.Sequential(
            nn.Linear(z_dim, d_model),
            nn.Tanh(),
        )
        nn.init.zeros_(self.gate[-2].weight)
        nn.init.ones_(self.gate[-2].bias)      # gate starts at ~0.73 (sigmoid(1))
        nn.init.zeros_(self.shift[-2].weight)
        nn.init.zeros_(self.shift[-2].bias)

    def forward(self, h: torch.Tensor, z: torch.Tensor) -> torch.Tensor:
        """
        h: [B, L, d]
        z: [B, z_dim]
        Returns modulated h [B, L, d].
        """
        gate  = self.gate(z).unsqueeze(1)    # [B, 1, d]
        shift = self.shift(z).unsqueeze(1)   # [B, 1, d]
        return h * gate + shift * 0.05
